#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-mbp
    username: hkh
    password: "$6$rounds=4096$changeme$replace_this_with_encrypted_hash"
  locale: en_US.UTF-8
  keyboard:
    layout: us
    variant: ''
  timezone: UTC
  apt:
    primary:
      - arches: [amd64]
        uri: http://archive.ubuntu.com/ubuntu
  ssh:
    install-server: true
    authorized-keys: []
    allow-pw: true

  storage:
    layout:
      name: existing
    config:
      - id: disk0
        type: disk
        match:
          path: /dev/nvme0n1
        ptable: gpt
        preserve: true

      # EFI (nvme0n1p1) — reuse
      - id: part-esp
        type: partition
        device: disk0
        number: 1
        preserve: true
        grub_device: true
      - id: fs-esp
        type: format
        fstype: fat32
        volume: part-esp
        preserve: true
      - id: mnt-esp
        type: mount
        device: fs-esp
        path: /boot/efi

      # macOS (nvme0n1p2) untouched — no entry

      # swap (nvme0n1p3) — reuse
      - id: part-swap
        type: partition
        device: disk0
        number: 3
        preserve: true
      - id: fs-swap
        type: format
        fstype: swap
        volume: part-swap
        preserve: true
      - id: mnt-swap
        type: mount
        device: fs-swap
        path: none

      # root (nvme0n1p4) — reformat to Btrfs
      - id: part-root
        type: partition
        device: disk0
        number: 4
        wipe: superblock
      - id: fs-root
        type: format
        fstype: btrfs
        volume: part-root
        label: root
      - id: mnt-root
        type: mount
        device: fs-root
        path: /
        options: [noatime,ssd,compress=zstd]

  packages:
    - linux-generic-hwe-24.04
    - btrfs-progs
    - build-essential
    - dkms
    - git
    - curl
    - wget
    - pipewire-audio
    - pipewire-pulse
    - wireplumber

  user-data:
    disable_root: false
    package_upgrade: true

  late-commands:
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get dist-upgrade -y
