#!/usr/bin/env bash
# refind-theme.sh
# Install the rEFInd boot manager + the "jellyskull" theme on MacBookPro14,3
# (Ubuntu 22.04 / kernel 5.15.x), giving a clean dual-boot picker for Ubuntu + macOS.
#
# This Mac can't show macOS from GRUB (GRUB/os-prober can't read APFS), so rEFInd is used
# as the picker: it chainloads Ubuntu's existing shim->GRUB and boots macOS directly. The
# "jellyskull" theme is a dark graphite (#2a2c30) background with monochrome white solid
# icons — a jellyfish for Ubuntu (22.04 "Jammy Jellyfish") and the Apple logo for macOS —
# plus an Apple-style border-light glow on the selected entry.
#
# Idempotent: safe to re-run. Backs up any existing refind.conf to refind.conf.dist.
#
# Tunables (env vars):
#   TIMEOUT=8                 seconds before the default (Ubuntu) auto-boots
#   MACOS_VG_GUID=<guid>      macOS APFS volume-group GUID (auto-detected from NVRAM if unset)
#   INSTALL_REFIND=1          set 0 to skip apt-installing rEFInd (assume already present)

set -Eeuo pipefail

# --- Helpers (same style as the other *-fix.sh scripts) ---
as_root() {
  if [[ $EUID -ne 0 ]]; then
    echo "Re-running with sudo..."
    exec sudo -E bash "$0" "$@"
  fi
}
info()  { echo -e "\e[1;34m[INFO]\e[0m $*"; }
warn()  { echo -e "\e[1;33m[WARN]\e[0m $*"; }
ok()    { echo -e "\e[1;32m[ OK ]\e[0m $*"; }
fail()  { echo -e "\e[1;31m[FAIL]\e[0m $*"; exit 1; }

as_root "$@"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
THEME_SRC="$SCRIPT_DIR/refind/jellyskull"
ESP="/boot/efi"
RDIR="$ESP/EFI/refind"
THEME_DST="$RDIR/themes/jellyskull"
REFIND_CONF="$RDIR/refind.conf"

TIMEOUT="${TIMEOUT:-8}"
INSTALL_REFIND="${INSTALL_REFIND:-1}"

[[ -d "$THEME_SRC" ]] || fail "Theme source not found: $THEME_SRC (run this from the repo checkout)."

info "Detected system:"
echo "  Product: $(cat /sys/class/dmi/id/product_name 2>/dev/null || echo 'unknown')"
echo "  Kernel : $(uname -r)"
[[ -d /sys/firmware/efi ]] || fail "Not booted in EFI mode — rEFInd requires EFI."
mountpoint -q "$ESP" || fail "ESP not mounted at $ESP."

# --- 1) Ensure rEFInd is installed and deployed to the ESP ---
if [[ "$INSTALL_REFIND" == "1" ]]; then
  if ! dpkg -s refind >/dev/null 2>&1; then
    info "Installing rEFInd…"
    echo 'refind refind/install_to_esp boolean true' | debconf-set-selections
    DEBIAN_FRONTEND=noninteractive apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y refind
  else
    info "rEFInd already installed."
  fi
fi
if command -v refind-install >/dev/null 2>&1; then
  info "Deploying rEFInd to the ESP (refind-install)…"
  refind-install >/dev/null 2>&1 || warn "refind-install returned non-zero (continuing)."
fi
[[ -f "$RDIR/refind_x64.efi" ]] || fail "rEFInd not present at $RDIR — install it first."

# Keep the menu clean: drop the auto-installed ext4 driver so rEFInd doesn't enumerate raw kernels
rm -rf "$RDIR/drivers_x64"

# --- 2) Detect the macOS volume-group GUID (for a single clean "macOS" entry) ---
DETECTED="$(efibootmgr -v 2>/dev/null | grep -i 'CoreServices' | tr '\\' '\n' \
  | grep -iE '^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$' | head -1 || true)"
MACOS_VG_GUID="${MACOS_VG_GUID:-$DETECTED}"
if [[ -z "${MACOS_VG_GUID:-}" ]]; then
  MACOS_VG_GUID="30696731-C77F-3DF6-A802-19AE82CD0371"
  warn "Could not auto-detect the macOS volume group; falling back to $MACOS_VG_GUID."
  warn "If macOS doesn't boot, find yours with:  efibootmgr -v | grep -i CoreServices"
else
  info "macOS volume-group GUID: $MACOS_VG_GUID"
fi

# --- 3) Install the jellyskull theme ---
info "Installing theme -> $THEME_DST"
mkdir -p "$RDIR/themes"
rm -rf "$THEME_DST"
cp -r "$THEME_SRC" "$THEME_DST"

# --- 4) Write refind.conf (back up any existing one first) ---
if [[ -f "$REFIND_CONF" && ! -f "$RDIR/refind.conf.dist" ]]; then
  cp "$REFIND_CONF" "$RDIR/refind.conf.dist"
  info "Backed up existing refind.conf -> refind.conf.dist"
fi
info "Writing refind.conf…"
cat > "$REFIND_CONF" <<EOF
# rEFInd config — MacBookPro14,3 dual-boot (Ubuntu + macOS)
# Generated by refind-theme.sh. Original shipped config saved as refind.conf.dist

timeout $TIMEOUT
use_nvram false
default_selection Ubuntu

scanfor internal,external,manual
scan_all_linux_kernels false

# Hide redundant/duplicate loaders. boot.efi is excluded so rEFInd stops auto-listing
# every macOS volume (the "preboot" + stale "untitled" tiles); the explicit macOS entry
# below replaces them. shim is kept as the single "Ubuntu" entry (chainloads GRUB).
dont_scan_files mmx64.efi,fbx64.efi,grubx64.efi,MokManager.efi,BOOTX64.EFI,bootx64.efi,boot.efi

showtools shutdown,reboot

# --- macOS: one explicit entry pointing at the known-good volume group ---
menuentry "macOS" {
    icon     /EFI/refind/themes/jellyskull/icons/os_mac.png
    volume   "Preboot"
    loader   /$MACOS_VG_GUID/System/Library/CoreServices/boot.efi
    graphics on
}

# --- custom theme ---
include themes/jellyskull/theme.conf
EOF

# --- 5) Make rEFInd first in the EFI boot order ---
RNUM="$(efibootmgr | sed -nE 's/^Boot([0-9A-Fa-f]{4})\*? .*rEFInd.*/\1/p' | head -1 || true)"
if [[ -n "$RNUM" ]]; then
  CUR_ORDER="$(efibootmgr | sed -nE 's/^BootOrder: (.*)/\1/p')"
  REST="$(echo "$CUR_ORDER" | tr ',' '\n' | grep -ivx "$RNUM" | paste -sd, -)"
  efibootmgr -o "${RNUM}${REST:+,$REST}" >/dev/null 2>&1 \
    && info "rEFInd (Boot$RNUM) set first in BootOrder." \
    || warn "Could not reorder BootOrder (rEFInd may already be first)."
else
  warn "No rEFInd NVRAM entry found to prioritize."
fi

# --- 6) Verify & report ---
ok "Done. Verifying:"
echo "---- theme files ----"
ls -1 "$THEME_DST" "$THEME_DST/icons" 2>/dev/null | sed 's/^/  /'
echo "---- boot entries ----"
efibootmgr | grep -E 'BootOrder|rEFInd|ubuntu|Mac OS X' || true
echo
ok "Reboot to see the menu. Default = Ubuntu after ${TIMEOUT}s; arrow/trackpad to pick macOS."
warn "Fallback if macOS ever fails to boot: hold the ⌥ (Option) key at the chime for Apple's picker."
